language: node_js
node_js: "stable"
before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH=$HOME/.meteor:$PATH
install:
  - npm install
script:
  - npm test
env:
  - NODE_ENV=test
cache:
  directories:
    - node_modules
    - $HOME/.meteor/
services:
  - mongodb
after_script:
- npm run coverage
